const disciplineQuotes = [
  "Protect today's streak.",
  "Momentum compounds.",
  "Stay with the process.",
  "Discipline feels better than regret.",
  "Stack another day.",
  "Keep the promise you made to yourself.",
  "Nobody can do this day for you.",
  "The strongest move is often invisible.",
  "You don't need motivation right now.",
  "You need one good decision.",
  "The future is built quietly.",
  "Keep showing up.",
  "Recovery is repetition.",
  "One more clean day.",
  "Keep your word.",
  "Keep moving forward.",
  "Today is enough.",
  "Consistency beats intensity.",
  "Trust the process.",
  "Keep stacking proof.",
  "Your actions are leading your emotions.",
  "The next right choice is enough.",
  "Stay present.",
  "Stay honest.",
  "Stay free.",
  "Freedom is earned daily.",
  "Make the next hour count.",
  "Stay in control.",
  "Keep the chain unbroken.",
];

const cravingQuotes = [
  "Just make it to bedtime.",
  "Cravings pass. Decisions remain.",
  "The urge is temporary.",
  "Don't negotiate with cravings.",
  "A craving is not a command.",
  "Pause before you choose.",
  "Choose tomorrow's pride over tonight's relief.",
  "The craving is loud because it is losing.",
  "You are stronger than this urge.",
  "You have survived every craving so far.",
  "You can survive this one too.",
  "Delay. Breathe. Decide.",
  "The urge weakens when ignored.",
  "This is temporary.",
  "The feeling is real. The command is not.",
  "Observe the craving. Don't obey it.",
  "Give it ten minutes.",
  "Wait before acting.",
  "The wave always falls.",
  "Cravings expire.",
  "You are bigger than this moment.",
  "You don't need alcohol to get through tonight.",
  "Not today.",
];

const recoveryQuotes = [
  "A slip is not the end.",
  "Keep fighting for yourself.",
  "Recovery isn't linear. Continue anyway.",
  "Don't count failures. Count returns.",
  "Get back on track quickly.",
  "One mistake doesn't erase progress.",
  "You are not starting over. You're continuing wiser.",
  "The goal is persistence.",
  "The comeback starts immediately.",
  "Every return is a victory.",
  "Recovery begins again today.",
  "You still know the way forward.",
];

const streakQuotes = [
  "Protect what you've built.",
  "Your streak is earned, not given.",
  "Every sober day changes the odds.",
  "This is what consistency looks like.",
  "You've already come too far to quit today.",
  "Every day counts twice: once today, once tomorrow.",
  "Protect your momentum.",
  "Every sober day is a vote for your future.",
  "Keep collecting victories.",
  "Keep your streak alive.",
  "One decision. One day. One victory.",
];

const identityQuotes = [
  "Future you is watching.",
  "You already survived worse days.",
  "You are building evidence.",
  "Protect your peace.",
  "You are learning to trust yourself again.",
  "Strength grows in silence.",
  "A better life is being built underneath this moment.",
  "You are becoming reliable to yourself.",
  "You are becoming the person you wanted to be.",
  "The hard path becomes the easy path.",
  "You don't need to feel strong to act strong.",
  "You are winning battles nobody sees.",
  "Peace is being built right now.",
  "The reward comes later. Continue.",
  "You're doing better than you think.",
  "Your future self will thank you.",
];

const encouragementQuotes = [
  "One day at a time.",
  "You only need today.",
  "A hard day sober still counts.",
  "Progress, not perfection.",
  "Small wins become big changes.",
  "The next hour matters more than yesterday.",
  "This feeling will change.",
  "Stay uncomfortable if it keeps you free.",
  "This moment decides more than it seems.",
  "Tomorrow starts now.",
];

const milestoneQuotes = [
  "Look how far you've come.",
  "The days are adding up.",
  "Momentum is becoming identity.",
  "Your consistency is paying off.",
  "You've proven you can do hard things.",
  "Another milestone. Another reason to continue.",
  "The person who started this journey would be proud.",
  "Every milestone was once just day one.",
  "You're building something real now.",
  "Keep going. The next milestone is already waiting.",
];

